

export const METASMK_CONNECT="METASMK_CONNECT"
export const METASMK_DISCONNECT="METASMK_DISCONNECT"



// add user actions
export const ADD_USER = {
    ADD_USER_INITIAL_API_CALL: "ADD_USER_INITIAL_API_CALL",
    ADD_USER_API_SUCCESS: "ADD_USER_API_SUCCESS",
    ADD_USER_API_FAIL: "ADD_USER_API_FAIL"
}